version: "3.9"

services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - ${HOST_APP_PORT:-80}:8080
    volumes:
      - .:/app
    environment:
      TZ: Europe/Warsaw

  db:
    image: postgres:13.1
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      TZ: Europe/Warsaw
      PGTZ: Europe/Warsaw
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES__DB:-app}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
